POST http://localhost:3001/users
Content-Type: application/json

{
    "email" : "test2@test.com",
    "password" : "123456789",
    "firstName" : "test2", 
    "lastName": "test2", 
    "schoolDistrict": "Goose Creek", 
    "zipCode" : 12345, 
    "phoneNumber": 6156156156
}

###


GET http://localhost:3001/sTasks?disabilities=["blind"]&age0To3=true&preK=false&elementarySchool=false&middleSchool=false&highSchool=false&eighteenPlus=false&adult=false
Content-Type: application/json

###

POST http://localhost:3001/sTasks
Content-Type: application/json

{
    "title" : "Request Services - Blind Childrens program",
    "link" : "https://www.hhs.texas.gov/services/disability/blind-visually-impaired/blind-childrens-vocational-discovery-development-program",
    "disabilities" : ["blind"],
    "age0To3" : true,
    "preK" : false,
    "elementarySchool" : false,
    "middleSchool" : false,
    "highSchool" : false,
    "eighteenPlus" : false,
    "adult" : false
}

###


GET http://localhost:3001/tasks?disability=["disabillity1","disability2","disability3"]
Content-Type: application/json
