POST http://localhost:3001/users
Content-Type: application/json

{
    "email" : "testChildren@test.com",
    "password" : "123456789",
    "firstName" : "testChildren", 
    "lastName": "test", 
    "schoolDistrict": "Goose Creek", 
    "zipCode" : 12345, 
    "phoneNumber": 6156156156,
    "children": ["63e5c4936d51fdbbbedb5503"]
}

###

PUT http://localhost:3001/children/63e5c4936d51fdbbbedb5503/completedTask
Content-Type: application/json

{ 
    "taskId": "63d2bd432decae8fde782e1e"
}

###

GET http://localhost:3001/children/63e5c4296d51fdbbbedb5500
Content-Type: application/json

###

GET http://localhost:3001/children/643b22b6ee8225a6684ac15b
Content-Type: application/json


###


GET http://localhost:3001/children/getChildrenByIdBatch/?id=["63e5c4936d51fdbbbedb5503"]
Content-Type: application/json


###

GET http://localhost:3001/tasks/byAttributes/?disabilities=["ADHD"]&priority=2
Content-Type: application/json

###

GET http://localhost:3001/tasks/byAttributes/?disabilities=["ADHD","disability2"]
Content-Type: application/json

###
POST http://localhost:3001/tasks
Content-Type: application/json

{
    "title": "Task 5",
    "details": "Call LIDDA based on county|https://resources.hhs.texas.gov/pages/find-services|https://resources.hhs.texas.gov/pages",
    "disabilities": ["ADHD", "disability1", "disability2"],
    "timePeriod": "monthly",
    "age": "Adult",
    "priority": 1
}

###
GET http://localhost:3001/tasks/byAttributes/?disabilities=["ADHD/ADD"]&age="Adult"
Content-Type: application/json

###
GET http://localhost:3001/tasks/getStats/?disabilities=["ADHD/ADD"]&age="Adult"&priority=2
Content-Type: application/json